### ISSUE TITLE
!cookie don't works in threads

### ISSUE THREAD

**Issue by ascpial** [Curiosity-org/Gipsy#188]
La commande cookie affiche une erreur quand elle est utilisée dans un thread :

```python
Traceback (most recent call last):
   File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/container/plugins/misc/misc.py", line 64, in cookie
    webhook: discord.Webhook = await ctx.channel.create_webhook(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'Thread' object has no attribute 'create_webhook'

```

**Comment by ascpial** [comment]
L'implémentation de #159 permettrai de résoudre les problèmes à régler dans les différents plugins d'un coup.
