### ISSUE TITLE
[help] !help command is broken

### ISSUE THREAD

**Issue by ascpial** [Curiosity-org/Gipsy#202]
Appeler la commande `!help` sans arguments affiche l'erreur suivante dans la console (avec discord.py en version `v2.0.0` et `v2.0.1`) :

```
Ignoring exception in command !help:
Traceback (most recent call last):
  File "/home/ascpial/Projets/Gipsy/venv/lib64/python3.11/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ascpial/Projets/Gipsy/venv/lib64/python3.11/site-packages/discord/ext/commands/help.py", line 943, in command_callback
    return await self.send_bot_help(mapping)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Help.send_bot_help() takes 1 positional argument but 2 were given```

**Comment by ZRunner** [comment]
Fixed in #210
