### ISSUE TITLE
!help plante

### ISSUE THREAD

**Issue by Majoras16** [Curiosity-org/Gipsy#206]
J'ai pas grand chose à dire, quand on fait "!help avec Gipsy Beta il dit qu'une erreur s'est produite.

**Comment by ZRunner** [comment]
Le traceback de l'erreur :
```
Traceback (most recent call last):
   File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/container/.local/lib/python3.11/site-packages/discord/ext/commands/help.py", line 948, in command_callback
    return await self.send_bot_help(mapping)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: Help.send_bot_help() takes 1 positional argument but 2 were given
 ```

**Comment by ascpial** [comment]
Fermé en tant que duplicata de #202.
